service: Starter
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    #stage: dev
    region: ap-south-1

functions:
    listDashboards:
        handler: handler.listDashboards
        timeout: 30 #seconds
        #memorySize: 128 #mb
        events:
            - http:
                  path: dashboards
                  method: post

    listReports:
        handler: handler.listReports
        timeout: 30
        events:
            - http:
                  path: reports
                  method: post

    listFields:
        handler: handler.listFields
        timeout: 30
        events:
            - http:
                  path: fields
                  method: post

    listApps:
        handler: handler.listApps
        timeout: 30
        events:
            - http:
                  path: apps
                  method: post

    storeAllDataToDB:
        handler: storeAllDataToDB.storeAllDataToDB
        timeout: 30
        events:
            - http:
                  path: storeAllDataToDB
                  method: post

    fetchPaginatedResults:
        handler: handler.fetchPaginatedResults
        timeout: 30
        events:
            - http:
                  path: fetchPaginatedResults
                  method: get

    fetchAndIndexTypeSenseData:
        handler: typeSense/typeSenseIndexData.fetchAndIndexTypeSenseData
        timeout: 30
        events:
            - http:
                  path: typeSenseIndexData
                  method: get

    search:
        handler: typeSense/search.search
        timeout: 30
        events:
            - http:
                  path: search
                  method: get

    storeSearches:
        handler: typeSense/storeSearches.storeSearches
        timeout: 30
        events:
            - http:
                  path: storeSearches
                  method: post

plugins:
    - serverless-offline
