org: punithraj
app: insightapp
service: InsightApp
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    #stage: dev
    region: ap-south-1

functions:
    listDashboards:
        handler: handler.listDashboards
        timeout: 30 #seconds
        #memorySize: 128 #mb
        events:
            - http:
                  path: dashboards
                  method: post
                  cors: true

    listReports:
        handler: handler.listReports
        timeout: 30
        events:
            - http:
                  path: reports
                  method: post
                  cors: true

    listFields:
        handler: handler.listFields
        timeout: 30
        events:
            - http:
                  path: fields
                  method: post
                  cors: true

    listApps:
        handler: handler.listApps
        timeout: 30
        events:
            - http:
                  path: apps
                  method: post
                  cors: true

    storeAllDataToDB:
        handler: storeAllDataToDB.storeAllDataToDB
        timeout: 30
        events:
            - http:
                  path: storeAllDataToDB
                  method: post
                  cors: true

    fetchPaginatedResults:
        handler: handler.fetchPaginatedResults
        timeout: 30
        events:
            - http:
                  path: list
                  method: get
                  cors: true

    overview:
        handler: handler.fetchOverviewResults
        timeout: 30
        events:
            - http:
                  path: overview
                  method: get
                  cors: true

    fetchAndIndexTypeSenseData:
        handler: typeSense/typeSenseIndexData.fetchAndIndexTypeSenseData
        timeout: 30
        events:
            - http:
                  path: typeSenseIndexData
                  method: get
                  cors: true

    search:
        handler: typeSense/search.search
        timeout: 30
        events:
            - http:
                  path: search
                  method: get
                  cors: true

    storeSearches:
        handler: typeSense/storeSearches.storeSearches
        timeout: 30
        events:
            - http:
                  path: storeSearches
                  method: post
                  cors: true

    updateMetaLabel:
        handler: handler.updateMetaLabel
        timeout: 30
        events:
            - http:
                  path: updateMetaLabel
                  method: post
                  cors: true

    updateClassification:
        handler: handler.updateClassification
        timeout: 30
        events:
            - http:
                  path: updateClassification
                  method: post
                  cors: true

    storeSecret:
        handler: secretsManager/secretStore.storeSecret
        timeout: 30
        events:
            - http:
                  path: login
                  method: post
                  cors: true

plugins:
    - serverless-offline
